<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ITL-LT-HP-REF-166-R08211509" failures="2" tests="7" name="Surefire test" time="121.858" errors="0" timestamp="2024-08-24T09:08:44 IST">
  <testcase classname="NAutomationTesting.ErrorValidationTest" name="ErrorMsg" time="0.556">
    <skipped/>
  </testcase> <!-- ErrorMsg -->
  <testcase classname="NAutomationTesting.ErrorValidationTest" name="ErrorMsg" time="0.523">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at NAutomationTesting.ErrorValidationTest.ErrorMsg(ErrorValidationTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- ErrorMsg -->
  <testcase classname="NAutomationTesting.ErrorValidationTest" name="getTexterror" time="0.558"/>
  <testcase classname="NAutomationTesting.ErrorValidationTest" name="getTexterror2" time="0.586"/>
  <testcase classname="NAutomationTesting.ErrorValidationTest" name="getTexterror3" time="0.46">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at NAutomationTesting.ErrorValidationTest.getTexterror3(ErrorValidationTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- getTexterror3 -->
  <testcase classname="NAutomationTesting.SubmitOrderTest" name="orderSubmit" time="8.377"/>
  <testcase classname="NAutomationTesting.SubmitOrderTest" name="orderSubmit" time="8.206"/>
</testsuite> <!-- Surefire test -->
